### ISSUE TITLE
Question: Hook for subtest start

### ISSUE THREAD

**Issue by mrbean-bremen** [pytest-dev/pytest-subtests#116]
Hi,
I'm a maintainer for `pyfakefs` and currently trying to make it play nice with `pytest-subtests` (see [this issue](https://github.com/pytest-dev/pyfakefs/issues/912)).
As `pyfakefs` patches the filesystem, I have to make sure that it is not active during reporting, so I currently suspend patching in `pytest_runtest_logreport` and resume it (provided the fixture is still active) in `pytest_runtest_call`. 
This does not work with subtests, as `pytest_runtest_logreport` is called before each subtest (which suspends patching), but  `pytest_runtest_call` is not, and I failed to find a hook to switch it back on before the next subtest. Is there a possibility (hook or otherwise) to get notified before a subtest is run which I can rely on?

Thanks!

**Comment by RonnyPfannschmidt** [comment]
currently there is no such hook, 

i just took note that the fix for https://github.com/pytest-dev/pyfakefs/issues/904 is incorrect
i recommended a tryfirst hookwrapper as the hookwrapper can undo the suspense in the hook itself

the implementation https://github.com/pytest-dev/pyfakefs/pull/907/files does not use a hookwrapper

a non hookwrapper tryfirst hook will never be invoked before hookwrappers and would always require a extra hack for undoing

**Comment by mrbean-bremen** [comment]
Thanks @RonnyPfannschmidt, I obviously got that wrong. Will fix this probably tomorrow.
