### ISSUE TITLE
Fixture to make all assertions into their own subtest

### ISSUE THREAD

**Issue by apnewberry** [pytest-dev/pytest-subtests#13]
Currently the usage requires a context manager, like this:

```python
def test(subtests):
    for i in range(5):
        with subtests.test(msg="custom message", i=i):
            assert i % 2 == 0
```

Often I want to have a subtest for each assert statement so that I can see all of the failures individually. So for example

```python
def test(assert_subtests):
    for i in range(5):        
        assert i % 2 == 0
```

I'm not sure what possible implementations would look like. Would this require a major reimplementation of the assertion rewriting?

**Comment by nicoddemus** [comment]
Hi @apnewberry,

Thanks for writing.

Indeed I don't think it is possible at the moment, because we need to trap the exception raised by the `assert` statement.

You are right that this would need a change in pytest's assertion rewriting, because it would need to rewrite the code to insert the `with` statement automatically.

This is out of the scope for this plugin, and I'm not sure we should add it to pytest itself either; seems like a source of problems waiting to happen.

Btw, you might check out [pytest-check](https://pypi.org/project/pytest-check/), which supports single-line-checks which report once instead of stopping at the point of the assertion failure, albeit you can't use plain assert statements.

Closing this then, feel free to follow with further questions though.
